# Generated by Django 6.1.1 on 2026-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_agentlog_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlog",
            name="message",
            field=models.TextField(),
        ),
    ]
